### PR TITLE
Format evidence repr more nicely

### PR DESCRIPTION
**Pull request by bgyori**
In #613 I changed the repr for Evidence objects to add some formatting. But the result has been pretty bad for long evidence sentences and annotations that weren't wrapped. This PR attempts to marginally improve the situation by adding some textwrapping and indentation when displaying evidences. One issue is that Statement.evidence is a plain list and so we can't really control if new lines are added between elements, this results in some strange looking formatting when displaying a list vs a single Evidence but still better than it was overall. Here is an example:
```
In [12]: stmts[10].evidence
Out[12]: 
[Evidence(source_api='reach',
          pmid='29085365',
          text='However, SOCS1 suppresses the effect of IFN-gamma on
                keratinocytes by inhibiting the JAK2 and STAT1 pathway.',
          annotations={
                        "found_by": "Negative_activation_syntax_1_verb",
                        "agents": {
                         "raw_text": [
                          "SOCS1",
                          "STAT1"
                         ]
                        },
                        "prior_uuids": [
                         "b8d9f340-50f1-48d3-bcbc-8b00dfea943c"
                        ],
                        "content_source": "pmc_oa"
                       })
 , Evidence(source_api='sparser',
          pmid='29235573',
          text='Western blot analysis of the effects of overexpression of SOCS1
                in DF-1 cells infected with IBDV (Supplementary Figure  xref )
                also demonstrated elevated levels of the IBDV VP2/3 protein but
                reduced levels of phosphorylated STAT1 compared to untransfected
                control cells (total levels of STAT1 were unchanged), indicating
                partial inhibition of virus-induced activation of STAT1 by SOCS1.',
          annotations={
                        "agents": {
                         "raw_text": [
                          "SOCS1",
                          "STAT1"
                         ]
                        },
                        "prior_uuids": [
                         "38017b06-491e-4359-b8de-b0aa516742b2"
                        ],
                        "content_source": "pmc_oa"
                       })

```

### CODE REVIEW

**Comment by bgyori** [comment]
[Fix formatting Evidence repr to work in Python 2](https://trello.com/c/669XoCDx/33-fix-formatting-evidence-repr-to-work-in-python-2)

**Comment by pagreene** [comment]
Python 2 issue should now be resolved, and the evidence looks pretty good in python 2:
```
Evidence(source_api='myhead',
         pmid='None',
         text='This is evidence. This is evidence. This is evidence. This is
               evidence. This is evidence. This is evidence. This is evidence.
               This is evidence. This is evidence. This is evidence. This is
               evidence. This is evidence. This is evidence. This is evidence.
               This is evidence. This is evidence. This is evidence. This is
               evidence. This is evidence. This is evidence. This is evidence.
               This is evidence. This is evidence. This is evidence. This is
               evidence. This is evidence. This is evidence. This is evidence.
               This is evidence. This is evidence. This is evidence. This is
               evidence. This is evidence. This is evidence. This is evidence.
               This is evidence. This is evidence. This is evidence. This is
               evidence. This is evidence. This is evidence. This is evidence.
               This is evidence. This is evidence. This is evidence. This is
               evidence. This is evidence. This is evidence. This is evidence.
               This is evidence. This is evidence. This is evidence. This is
               evidence. This is evidence. This is evidence. This is evidence.
               This is evidence. This is evidence. This is evidence. This is
               evidence. This is evidence. This is evidence. This is evidence.
               This is evidence. This is evidence. This is evidence. This is
               evidence. This is evidence. This is evidence. This is evidence.
               This is evidence. This is evidence. This is evidence. This is
               evidence. This is evidence. This is evidence. This is evidence.
               This is evidence. This is evidence. This is evidence. This is
               evidence. This is evidence. This is evidence. This is evidence.
               This is evidence. This is evidence. This is evidence. This is
               evidence. This is evidence. This is evidence. This is evidence.
               This is evidence. This is evidence. This is evidence. This is
               evidence. This is evidence. This is evidence. This is evidence.
               This is evidence. This is evidence.',
         annotations={
                       "bug": "ant"
                      })
```

**Comment by pagreene** [comment]
Got another weird error related to http requests.
```
======================================================================
ERROR: indra.tests.test_uniprot_client.test_get_sequence
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/sorgerlab/indra/indra/tests/test_uniprot_client.py", line 114, in test_get_sequence
    seq = uniprot_client.get_sequence('P00533')
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/functools32/functools32.py", line 400, in wrapper
    result = user_function(*args, **kwds)
  File "/home/travis/build/sorgerlab/indra/indra/databases/uniprot_client.py", line 363, in get_sequence
    res = requests.get(url)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/requests/sessions.py", line 659, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/requests/sessions.py", line 238, in resolve_redirects
    **adapter_kwargs
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```
Perhaps there is a problem with Travis right now? This certainly doesn't _appear_ to be related to this PR.

**Comment by bgyori** [comment]
This is perfect so far! After some testing I feel like we should go a bit further and include the `context` and the `epistemics` attributes in the repr as well which were missing for some reason. In the case of `context`, we could format it by calling its to_json method to get a dict and then formatting it like `annotations`, and since `epistemics` is a dict to begin with, it can be formatted exactly like `annotations`. Yet another useful extension would be to check if the `source_id` attribute is not None (this will typically be the case for evidences from pathway databases) and if has a value then add a line for it to the repr. Thanks!

**Comment by bgyori** [comment]
Looks great, @pagreene!

**Pull request merged**
