### PR TITLE
RAS Machine CLI

### LINKED ISSUE #295: Refactor CLI for RAS Machine
The RAS Machine's CLI has a couple of problems with reproducibility:

- all machine folders need to be inside the `/indra/models/rasmachine` folder
- CX uploads default to naming networks `rasmachine`
- CLI with parsing of `sys.argv` isn't extensible for later (My secret desire is to have another CLI function that loads the most recent pickle from the folder and lets me export it in different formats using the different assemblers)

### PR DESCRIPTION
**Pull request by cthoyt**
Adds a CLI for the RAS Machine that closes #295

### CODE REVIEW

**Comment by bgyori** [comment]
Thanks, are you still adding things?

**Comment by cthoyt** [comment]
I just added a stub for a function that will increment a model based on a file whose lines are PMIDS (or from stdin) but this is going to require some refactoring and I think I better leave that to you. I'm all done for now

**Comment by cthoyt** [comment]
Good thing I checked - there was a typo XD

**Comment by bgyori** [comment]
This is really nice, thank you!

**Pull request merged**
