### PR TITLE
Tag tests with attributes

### PR DESCRIPTION
**Pull request by pagreene**
Implement some attributes to the nosetests. Use these attributes to skip tests that require nonpublic environment variables during a pull request in travis tests. This pull request should test that feature.
 
Addresses: https://github.com/sorgerlab/indra/issues/354

### CODE REVIEW

**Comment by bgyori** [comment]
This looks good! The only issue is that a number of tests (for instance in the HGNC and UniProt clients) that are currently tagged as webservice actually use off-line resource files. I will take a look at these and remove the webservice tag where applicable.

**Comment by pagreene** [comment]
Fair enough. I was in many cases guessing. And there is the opposite problem in some cases, such as with the trips tests, which I think go out to a web service. Feel free to add more tags, especially nonpublic tags, where fitting. I suspect I missed some of those, and thus the travis test will not be green, but at least won't have not failed for some of the wrong reasons.

**Comment by pagreene** [comment]
In my first "Make s3 nonpublic" commit, I had accidentally edited the pmc file, not the s3 file. Ben's "Fix wrong webservice/nonpublic tags" commit fixed those bugs.

**Comment by pagreene** [comment]
Well, the change to travis definitely seems to be working. Now it just a matter of actually classifying things correctly.

**Pull request merged**
