### PR TITLE
Make sure PMID is converted to string in PyBEL Assembler

### PR DESCRIPTION
**Pull request by cthoyt**
This should address https://github.com/sorgerlab/indra/issues/1184#issuecomment-717783584

### CODE REVIEW

**Comment by johnbachman** [comment]
I wonder if we should handle this in the processor instead, because the PMIDs in the evidence objects should always be strings, not ints.

**Comment by bgyori** [comment]
Yes, this is a Reacome/BioPAX-specific issue that is better handled in `indra.sources.biopax`. The new Statement validator (https://github.com/sorgerlab/indra/pull/1172) can be used to ensure that the statements ingested from a given source are valid, and we can make changes in the processor until these issues are addressed. I'll finish this up today.

**Comment by bgyori** [comment]
Based on the things I looked into, this may not be related to how content is obtained from BioPAX, see my comment on #1184.

**Comment by bgyori** [comment]
Given what we found in #1184 and #1187, is this PR still needed? I don't think any sources produce int PMIDs currently, especially with the validation module in place, so this may not be needed.

**Comment by cthoyt** [comment]
All gucci! Not sure exactly what fixed it, but I'll take it.

Running on:

```python
>>> import indra.util.get_version
>>> indra.util.get_version.get_version()
'1.18.0-5a1ec8a80ea756adc6bcc2b65dbf5779631e8327'
```

Ran this code:

```python
import pybel
import pybiopax
import indra.sources.biopax

biopax_model = pybiopax.model_from_owl_url('https://reactome.org/ReactomeRESTfulAPI/RESTfulWS/biopaxExporter/Level3/1643685')
bp = indra.sources.biopax.process_model(biopax_model)
print(len(bp.statements))

graph = pybel.from_indra_statements(bp.statements)
graph.summarize()
indra vbf0d420b-1169-452d-9584-42da61cdd94b
Number of Nodes: 1370
Number of Edges: 4274
Number of Citations: 312
Number of Authors: 0
Network Density: 2.28E-03
Number of Components: 47
Number of Warnings: 0
```

**Pull request closed without merging**
