### PR TITLE
Add OBO resources, clients, and tests for HP, EFO, and DOID

### LINKED ISSUE #927: Add additional resources from OBO
I was discussing with Ben via Slack about including the Human Phenotype Ontology, the Experimental Factor Ontology, and the Disease Ontology as additional ways of describing phenotypes and clinical measurements. All of these resources are available as OBO, so I think it would make sense to have a standardized OBO loader - these files usually come with xrefs and synonyms, too. Will send a PR

### PR DESCRIPTION
**Pull request by cthoyt**
Closes #927 

This gets the names, identifiers, xrefs, and synonyms from the OBO files.

### CODE REVIEW

**Comment by bgyori** [comment]
This looks great, thanks! The only thing is, we're keeping INDRA Python 3.5 compatible and so the f-strings in obo_client.py, sadly, will need to be replaced.

**Comment by cthoyt** [comment]
f-strings removed :/ and synonyms/xrefs added!

**Comment by bgyori** [comment]
I also removed the type hints :) Travis tests should pass now. Just saw your change to JSON to have xrefs, I think that's great because that will allow us to resolve redundancies with MeSH, etc.

**Comment by cthoyt** [comment]
Summary of available xrefs (cutoff < 50):

## DOID

```
('UMLS_CUI', 6666)
('NCI', 4716)
('OMIM', 4420)
('ICD10CM', 4219)
('SNOMEDCT_US_2018_03_01', 3915)
('MESH', 3336)
('ICD9CM', 2594)
('NCI2004_11_17', 1878)
('GARD', 1631)
('ORDO', 1404)
('MTHICD9_2006', 489)
('ICD9CM_2006', 455)
('CSP2005', 431)
('EFO', 132)
('MTH', 100)
...
```

## HP
```
('UMLS', 13057)
('SNOMEDCT_US', 4671)
('MSH', 2174)
('Fyler', 222)
('NCIT', 216)
('MEDDRA', 93)
...
```

## EFO
```
('DOID', 3186)
('ICD10', 2726)
('MONDO', 2612)
('UMLS', 2374)
('NCIt', 2167)
('ICD9', 2102)
('NCIT', 2014)
('MSH', 2001)
('SCTID', 1779)
('MESH', 1647)
('SNOMEDCT', 1491)
('MedDRA', 1026)
('PMID', 1009)
('OMIM', 768)
('COHD', 600)
('Orphanet', 586)
('GARD', 551)
('ICDO', 315)
('ONCOTREE', 285)
('Wikipedia', 249)
('HP', 235)
('MO', 129)
('UMLS_CUI', 70)
('BTO', 64)
('ORDO', 58)
('NIFSTD', 57)
...
```

**Pull request merged**
