### PR TITLE
Update rdflib version to 4.2.2

### PR DESCRIPTION
**Pull request by cthoyt**
I'm not sure if this will pass - we'll let travis decide that

### CODE REVIEW

**Comment by bgyori** [comment]
Hi @cthoyt, the reason we fixed rdflib to version 4.2.1 is that there was a serious increase in time taken for some of the SPARQL queries that INDRA does with newer versions of rdflib. I can't recall exactly which modules were affected but we would need to do more investigation and testing before considering to merge this. Is there a reason to increase the version that would motivate this?

**Comment by bgyori** [comment]
I guess one solution would be to deprecate the BEL/RDF processor and just keep the PyBEL integration - I would want to check if the other places where we use SPARQL queries are also affected by 4.2.2 first so it could take a little while.

**Comment by cthoyt** [comment]
Do we have a good way to check if PyBEL minimally duplicates all of the functionalities of the BEL/RDF processor?

**Comment by bgyori** [comment]
Informally I'm pretty confident that it does but we could set up a formal comparison at the Statement level to check - good idea.

**Comment by bgyori** [comment]
Given #982 this can now be closed

**Pull request closed without merging**
