### PR TITLE
Additional eidos groundings

### PR DESCRIPTION
**Pull request by adarshp**
This PR adds functionality to process additional Eidos groundings (WDI, FAO)

### CODE REVIEW

**Comment by bgyori** [comment]
Thanks, this is a good start but the scored groundings are used in a number of other assembly components and I will need to go in an reimplement those too to be able to handle a deeper dict structure.

**Comment by adarshp** [comment]
Potentially you could save some work by flattening the structure - instead of having

```python
db_refs['EIDOS'] = {
'un': [('x', 1.0), ...]
'fao': [('y', 1.0), ...]
...
}
```

You could do:
```python
db_refs = {
'un': [('x', 1.0),...]
'fao': [('y', 1.0), ...]
...
}
```

Just a thought..

**Comment by bgyori** [comment]
Yes, that's a good idea, I guess UN, FAO, WDI are not Eidos-specific so we can do away with the EIDOS key and use those instead - it would also solve this issue since I would just need to change EIDOS to UN in a couple of places. I'd capitalize it to be consistent with other db_refs keys, like
```
db_refs = {
'UN': [('x', 1.0),...]
'FAO': [('y', 1.0), ...]
```
What do you think? I can add this on top of your branch tonight of that sounds good to you.

**Comment by adarshp** [comment]
Sounds good to me!

**Comment by bgyori** [comment]
This should work now according to what we discussed above, let me know if you run into any issues!

**Comment by adarshp** [comment]
Works great, thanks!

**Pull request merged**
