### PR TITLE
Json LD parsing functionality

### PR DESCRIPTION
**Pull request by adarshp**
Added JSON-LD parsing functionality

### CODE REVIEW

**Comment by adarshp** [comment]
#417

**Comment by bgyori** [comment]
This looks great, thanks @adarshp! Since the processing code of JSON and JSON-LD dicts is distinct, I'm wondering if we should make two separate classes inside process_eidos.py, i.e. EidosJsonProcessor and EidosJsonLdProcessor which can then each contain the relevant methods for the two formats - I can do this if you agree. Another nice addition would be to add another option to the EidosReader to call EidosSystem to produce JSON-LD output (rather than its current default of the simple JSON of OdinMentions) - again, I could add this pretty easily but you can also work on it if you want. Let me know!

**Comment by adarshp** [comment]
1. I think two separate classes sounds fine. An alternative that might keep things more unified would be to split the logic by checking the extension of the input file - if it is .json, it could be processed as a JSON, and if it is .jsonld, it could be processed as JSON-LD. However, I'm not sure if this might be too brittle an approach or not.

2. I think it would definitely be good to add the option to have EidosSystem produce JSON-LD output.

I'll take you up on your offer to implement these features, thanks!

**Comment by bgyori** [comment]
Alright, I added the following things:
- separated the two processors, both in processor.py
- implemented reading into a JSON-LD string via the EidosReader (this will work once https://github.com/clulab/eidos/pull/177 is merged)
- added the extraction of Evidence from JSON-LD - currently evidence text and the rule used to get the extraction are added to the evidence of each Statement
- added a test

There is now an optional argument to `process_text` called `out_format` which defaults to the "old" `json` but can also be set to `json_ld`, for instance
```
from indra.sources import eidos
ep = eidos.process_text('fuel prices decrease water trucking', out_format='json_ld')
```

**Pull request merged**
